import localFont from 'next/font/local'
import '../globals.css'
import '@/styles/index.css'
import Head from 'next/head'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const JosefinSans = localFont({
  src: '../../assets/fonts/JosefinSans-VariableFont_wght.ttf',
  display: 'swap',
  variable: '--font-josefin'
})

const Audrey = localFont({
  src: '../../assets/fonts/Audrey-Normal.otf',
  display: 'swap',
  variable: '--font-audrey'
})

export default function RootLayout({children}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={`${JosefinSans.variable} ${Audrey.variable} font-sans`}>
    <Head>
      <meta charSet="utf-8" />
    </Head>
    <body className="max-w-[1440px] mx-auto">
    <main>{children}</main>
    </body>
    </html>
  )
}
